### ISSUE TITLE
`global_namespace_import ` disabled but `PhpCsFixerCustomFixers/no_import_from_global_namespace` enabled

### ISSUE THREAD

**Issue by bendavies** [ergebnis/php-cs-fixer-config#1008]
Hi  there,

Do you know why

[`global_namespace_import`](https://cs.symfony.com/doc/rules/import/global_namespace_import.html) is disabled but [`PhpCsFixerCustomFixers/no_import_from_global_namespace`](https://github.com/kubawerlos/php-cs-fixer-custom-fixers#noimportfromglobalnamespacefixer) is enabled?

Can't the core `global_namespace_import` be configured to do the same thing with `['import_classes' => false, 'import_constants' => false, 'import_functions' => false]`

Thanks

**Comment by localheinz** [comment]
That's a good point - thank you, @bendavies!
