### ISSUE TITLE
Why forcing all the builtin rules to be configured?

### ISSUE THREAD

**Issue by linuxjuggler** [ergebnis/php-cs-fixer-config#2]
Hey,

I am trying to build a ruleset for Laravel 6 based on this [gist](https://gist.github.com/laravel-shift/cab527923ed2a109dda047b97d53c200), while am trying to make sure that tests pass I faced the problem where many of the default rules are not set within the gist and this test always fails **testAllBuiltInRulesAreConfigured**.

I was wondering why do you force all the builtin rules to be configured?

Thanks

**Comment by localheinz** [comment]
Hello @linuxjuggler!

Thank you for opening an issue and asking for an explanation. 

The idea behind that test is that we want to make sure that all available fixers are either enabled or disabled explicitly. This also helps when receiving updates of [`friendsofphp/php-cs-fixer`](https://github.com/FriendsOfPHP/PHP-CS-Fixer), perhaps via [Dependabot](https://dependabot.com), which brings in new fixers: the failing test will indicate that new fixers have been provided by the update.

For an example, see https://github.com/localheinz/php-cs-fixer-config/pull/213:

- with https://github.com/localheinz/php-cs-fixer-config/pull/213/commits/aee85269c50508fb5d2d977eaa0800d3da207ccf Dependabot opened a pull request updating `friendsofphp/php-cs-fixer`, pulling in new fixers, which resulted in a failing build
- with https://github.com/localheinz/php-cs-fixer-config/pull/213/commits/4ca4f6c3d1904d59c2e10b7b10fe1a800fb67bc1, I disabled the newly added fixers to fix the build
- as follow-ups, with https://github.com/localheinz/php-cs-fixer-config/pull/214, https://github.com/localheinz/php-cs-fixer-config/pull/215, https://github.com/localheinz/php-cs-fixer-config/pull/216, https://github.com/localheinz/php-cs-fixer-config/pull/217, https://github.com/localheinz/php-cs-fixer-config/pull/218 I enabled the fixers

On the long run, this helps keeping up-to-date with newly added fixers!

Perhaps you find https://github.com/ergebnis/php-cs-fixer-config-template a better starting point? I also added a [Motivation](https://github.com/ergebnis/php-cs-fixer-config-template#motivation) section there, maybe it helps?

**Comment by linuxjuggler** [comment]
Fair enough, thanks @localheinz for the explanation.

I'll check the template and might send a PR once I got my tests to pass.

**Comment by localheinz** [comment]
Thank you, @linuxjuggler!
